### ISSUE TITLE
Fix problems reported by Codefactor

### ISSUE THREAD

**Issue by satyamtg** [openzim/sotoki#120] opened 2020-04-09 22:15 UTC
The sotoki.py file has a codefactor score of 'F'. We can improve this by solving the problems as mentioned here - https://www.codefactor.io/repository/github/openzim/sotoki/issues

**Comment by rgaudin** [comment] 2020-04-10 10:43
Agrees ; I think it's one of the first scraper.
I don't think it's a good first issue though because fixing this means:

* making sure we have a stable version before. That will change a lot of code and render merging bug fixes difficult.
* change a lot of code ; xml parsing, use requests instead of urlib, etc. So a lot of testing required to make sure we don't introduce regressions.
* use the opportunity to set code formatting (black, as for the other scrapers)

We should probably wait for the switch to pyzim to be completed and tested before we do it.

**Comment by rgaudin** [comment] 2021-06-06 10:54
Closing as current master has no such issue and it's already in repo rules.

**Closed by rgaudin** 2021-06-06 10:54 UTC
Labels: enhancement, good first issue
