### ISSUE TITLE
Process dies at the end with "KeyboardInterrupt"

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#255] opened 2022-05-14 14:50 UTC
```
Traceback (most recent call last):
  File "/usr/local/bin/sotoki", line 33, in <module>
    sys.exit(load_entry_point('sotoki==2.0.0', 'console_scripts', 'sotoki')())
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/__main__.py", line 15, in main
    entry()
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/entrypoint.py", line 344, in main
    sys.exit(scraper.run())
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/scraper.py", line 190, in run
    return self.start()
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/scraper.py", line 244, in start
    Global.img_executor.shutdown()
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/utils/executor.py", line 153, in shutdown
    self.join()
  File "/usr/local/lib/python3.8/site-packages/sotoki-2.0.0-py3.8.egg/sotoki/utils/executor.py", line 135, in join
    t.join(1)
  File "/usr/local/lib/python3.8/threading.py", line 1015, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/usr/local/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

For example at https://farm.openzim.org/pipeline/1f5e91e258211b4cac7fc726/debug

**Comment by rgaudin** [comment] 2022-05-17 10:36
Received a SINGINT, most probably by worker owner after he'd have seen the process spend more than 30mn joining threads. Marking this a duplicate of #253

**Closed by rgaudin** 2022-05-17 10:36 UTC
Labels: bug, duplicate
