### ISSUE TITLE
wrong pictures in askubuntu.com_en_all_2023-11

### ISSUE THREAD

**Issue by kelson42** [openzim/sotoki#295] opened 2024-03-05 13:21 UTC
From kiwix-tools created by [ristein](https://github.com/ristein): kiwix/kiwix-tools#662  

hey there,
I just mentioned all pictures in askubuntu.com_en_all_2023-11 are wrong.
As example I looked at these two random links:
https://askubuntu.com/questions/372607/how-to-create-a-bootable-ubuntu-usb-flash-drive-from-terminal
https://askubuntu.com/questions/809237/how-to-fix-the-destination-is-read-only-error-on-hdd-partition
On the website are correct images but in the zim-file are different ones, I don't know where these are from.
Using firefox and docker like this:
docker run -d --name kiwix -p 10234:8080 -v /path/kiwix/:/data --restart unless-stopped ghcr.io/kiwix/kiwix-serve /data/*.zim
using latest kiwix version 3.6.0

**Comment by kelson42** [comment] 2024-03-05 13:21
ZIM is OK, https://library.kiwix.org/viewer#askubuntu.com_en_all_2023-11/questions/372607/how-to-create-a-bootable-ubuntu-usb-flash-drive-from-terminal

Error is probably in your docker command line, you don't follow the README properly: 
https://github.com/kiwix/kiwix-tools/blob/main/docker/server/README.md

**Comment by kelson42** [comment] 2024-03-05 13:21
> ZIM is OK, https://library.kiwix.org/viewer#askubuntu.com_en_all_2023-11/questions/372607/how-to-create-a-bootable-ubuntu-usb-flash-drive-from-terminal
> 
> Error is probably in your docker command line, you don't follow the README properly: https://github.com/kiwix/kiwix-tools/blob/main/docker/server/README.md

it is not, in your link, the photo is wrong, on live website there is the correct one
live:
![image](https://github.com/kiwix/kiwix-tools/assets/55446611/a3cfee92-5bd9-4689-8d03-7d032a874968)
zimit:
![image](https://github.com/kiwix/kiwix-tools/assets/55446611/705d814b-190c-4ff0-843c-7c9876b9280b)

**Comment by rgaudin** [comment] 2024-03-05 14:37
It looks like #284 which was fixed in July 2023.
The problem is that image URL online is 10 chars long: [3857321170.webp](https://library.kiwix.org/content/askubuntu.com_en_all_2023-11/images/3857321170.webp) so it's an adler32

There has been a sotoki 2.0.2 release on 2023-10-31 and the 2023-11 stackoverflow was [started on 2023-11-23](https://farm.openzim.org/pipeline/9e345257-94a5-4134-9f75-3db4fa0ba992/debug) and using 2.0.2

**Comment by benoit74** [comment] 2024-03-05 16:58
> There has been a sotoki 2.0.2 release on 2023-10-31

Nope, 202**2**, not 202**3** ; fix has never been released.

=> known issue, already fixed in `main`, never released

**Closed** 2024-03-05 17:03 UTC
Labels: bug
