### ISSUE TITLE
Fulltext search does not work in physics.stackexchange zim file

### ISSUE THREAD

**Issue by tigran123** [openzim/sotoki#128] opened 2020-04-12 09:35 UTC
As mentioned at the end of #96 trying to search in the latest physics.stackexchange file does not produce all search hits. Instead, it gives a list of a few choices and this list does NOT contain the option "containing 'text'" and so one cannot search for all articles containing the 'text'. Other zim files (tested mathematica.stackexchange and mathematics.stackexchange) have no such problem, i.e. the list contains an option "containing 'text'" and this produces the correct list of all search hits, as expected.

**Comment by satyamtg** [comment] 2020-04-12 09:40
@tigran123 have you tested this on previous physics.stackexchange.com ZIMs? Like I want to get an idea on the timeline of this issue, whether this has developed due to recent work or if it persists unnoticed from long back.

**Comment by tigran123** [comment] 2020-04-12 09:42
Unfortunately, being optimistic, I deleted the old physics.stackexchange.com zim file :)

**Comment by kelson42** [comment] 2020-04-12 09:42
@satyamtg Please let me handle this, this is probably not related at all with Sotoki. I'm investigating

**Comment by kelson42** [comment] 2020-04-12 10:25
For the moment, I believe this is somehow related to https://github.com/kiwix/kiwix-lib/issues/339. As this bug shoudl be fixed in the next days, I will wait for that first.

**Comment by kelson42** [comment] 2020-04-13 13:19
So, the problem is that there is not fulltext index in this ZIM file.
```
zimdump -l physics.stackexchange.com_en_all_2020-04.zim
```

**Comment by tigran123** [comment] 2020-04-13 13:27
Excellent, so can someone rebuilt the zim file with the fulltext index included, please?

**Comment by kelson42** [comment] 2020-04-13 13:43
@tigran123 This is two bugs/weaknesses which correlate since last September here. So, good catch. Fixes are on their paths. Hopefully I can restart a scrape later today. Thank you again

**Closed** 2020-04-13 15:24 UTC
Labels: bug

**Comment by tigran123** [comment] 2020-04-13 16:36
The issue is closed, does that mean there is a working physics.stackexchange zim file ready to be tested?

**Comment by rgaudin** [comment] 2020-04-13 16:39
No, it means the bug in the code have been fixed. This is separate from the zim file creations.  @kelson42's message looks clear enough : a new file **will be** created soon.

**Comment by tigran123** [comment] 2020-04-13 16:42
Thank you, I will test the zim file when it is ready.
