### ISSUE TITLE
Header is very different depending on the size of the screen

### ISSUE THREAD

**Issue by mossroy** [openzim/sotoki#237] opened 2021-08-20 16:56 UTC
### Step 2 : What is your environment ?
  * browser / app : kiwix-js on Chromium 92.0.4515.159
  * version of the software you use : git commit id 9e7c1e9fb32fdc0372d186c2cae0308d4f892c73 (latest of branch Add-instructions-to-compile-zstddec-with-docker, but should be the same on master)
  * device / operating system : Ubuntu 20.04
  
### Step 3: Describe the problem:

It's a very minor issue, only something that I find cosmetically strange :

  * With a large window/screen, the header looks like this :
![image](https://user-images.githubusercontent.com/890923/130267182-978f7cce-7d55-4628-bbe2-c56f1bd5dd23.png)

  * With a smaller window/screen, it looks like this : 
![image](https://user-images.githubusercontent.com/890923/130267273-2f9a2a2d-a709-470a-9341-e0828a21f23c.png)

The fact that the content uses responsive design is great (the content adapts itself to the screen size). In particular, it's very relevant that the Questions/Tags/Users/About links are moved to the top on small screens, instead of being on the side.

What I find surprising is that the style is very different : the logo and black background only appear on small screens

#### Steps to reproduce:

  1. download http://tmp.kiwix.org/alcohol_meta_stackexchange_com_2021-08.zim
  2. open it with latest nightly of kiwix-js (from https://download.kiwix.org/nightly/), or another recent kiwix client
  3. resize your browser window
  
  * What should be the behaviour from your point of view? How do you expect the service to work? IMHO the UI should be a bit more consistent with small and large screens, at least in terms of colors

**Comment by rgaudin** [comment] 2021-08-20 17:55
Yes, that was surprising for me too when I saw that on stack exchange websites. We've somehow replicated what was online. SE's website has changed a bit since we replicated their style. I believe this is an ongoing process.

We adapted it a bit because it was relying on JS and using different pages (not responsiveness) for About page for instance but the top bar with the inverted colors is theirs.

We'll probably revisit (copy-again) their new style when we're confident it's stable.

Not planning on doing anything for this at the moment. Closing until additional feedback requests we act upon it.

**Closed by rgaudin** 2021-08-20 17:55 UTC
Labels: wontfix, upstream

**Comment by mossroy** [comment] 2021-08-20 18:38
All right, no problem.

By the way, if you can use "only" CSS-based responsive design (without javascript for that) in next version, it would allow it to work on devices that only support our jQuery mode (that does not handle javascript).
With the file mentioned above, the Questions/Tags/Users/About are still on the left side of small screens in jQuery mode. Even if the black header appears.

I know it's not always possible to avoid javascript : just keep in mind that some devices won't be able to run any javascript with kiwix-js. We do our best to keep the basic features and content in this case.

**Comment by rgaudin** [comment] 2021-08-20 18:43
it's already the case in master. maybe this zim is too old. I'll upload a newer version for you

**Comment by rgaudin** [comment] 2021-08-21 19:26
@mossroy https://mirror.download.kiwix.org/zim/.hidden/dev/alcohol_meta_stackexchange_com_2021-08.zim

**Comment by mossroy** [comment] 2021-08-22 08:11
I unfortunately have the same behavior with 2021-07 and 2021-08 versions of this ZIM file

**Comment by kelson42** [comment] 2021-08-22 08:28
@mossroy I guess this problem is reproducible with the responsive mode of Firefox. I would recommend to open a ticket in sotoki with exact screen resolution to use and screenshot.

**Comment by rgaudin** [comment] 2021-08-22 08:32
In case that was not clear from my comment : this zim has a similar UI (said we won't change it now) but doesn't rely on JS sir it. 

JS-specific features are:
- dates turned into a delta
- code highlighting
- math rendering

**Comment by mossroy** [comment] 2021-08-22 16:24
The exact screen width when this happens is 640px, and it's indeed reproducible with the dev tools of Firefox (in jQuery mode) : 

![image](https://user-images.githubusercontent.com/890923/130362392-e0bff6c8-4986-407f-8603-f55df4d695e6.png)

Thanks @rgaudin for the clarification. If no javascript is involved for the responsive design, it needs more investigation on our side (@Jaidroid an I) to understand why : maybe a CSS file is missing, or does not apply properly. If it's something that can be easily fixed on sotoki side, we'll create a new issue.

**Comment by rgaudin** [comment] 2021-08-22 16:31
Not sure I'm following. Your issue is not about that design switch but the fact that responsiveness is broken in kiwix-js right? Indeed I can reproduce this in kiwix-js (firefox ext nightly) but not on [kiwix-serve](https://dev.library.kiwix.org/alcohol_meta_stackexchange_com_2021-08/C/questions)

**Comment by mossroy** [comment] 2021-08-22 17:02
Yes, you understood correctly.
To avoid polluting this issue here, I've opened https://github.com/kiwix/kiwix-js/issues/756 (on kiwix-js side, for investigation)
